# Generated by Django 3.1.5 on 2021-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('ItemPrice', models.IntegerField()),
            ],
        ),
    ]
